/* DO NOT EDIT THIS FILE
 * - strawhat_shell.h (Part of StrawHat VM)
 *   Provides the prototype to grant shell access to StrawHat functions.
 */

#ifndef STRAWHAT_SHELL_H
#define STRAWHAT_SHELL_H

extern int g_debug_mode;
void shell(); // Run the Virtual System with Shell Access

#endif
