/* Do Not Edit this File
 */

#ifndef SMALLFP_H
#define SMALLFP_H

#include "smallfp_precision.h"
#include "common_structs.h"

/* Public Types for Use */
typedef unsigned short smallfp_s;

/* We have no doubles or floats in this system */
#define double long // Use a signed 64-bit integer type.
#define float int // Use a signed 32-bit integer type.

/* Public SMALLFP Library Functions */
smallfp_s toSmallFP(Number_s *num);
int toNumber(Number_s *num, smallfp_s value);
smallfp_s negSmallFP(smallfp_s value);
smallfp_s addSmallFP(smallfp_s val1, smallfp_s val2);
smallfp_s subSmallFP(smallfp_s val1, smallfp_s val2);
smallfp_s mulSmallFP(smallfp_s val1, smallfp_s val2);

#endif
