/* DO NOT EDIT THIS FILE
 * - symtab.h (MUAN Calculator)
 */

#ifndef SYMTAB_H
#define SYMTAB_H

#include "smallfp.h"

void initialize_symtab();
int sym_exists(const char *name);
smallfp_s get_value(const char *name);
void insert_symbol(const char *name, smallfp_s value);
void teardown_symtab();

#endif
