# Philip Stavrev G01463574
# CS 262, Lecture Section 001
# Project 2

CC = gcc
CFLAGS = -Wall -pedantic-errors
TARGET = p2_pstavrev_202

all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c -lm

clean:
	rm -f $(TARGET)

